# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
# Use an official Node.js runtime as a parent image
FROM node:18-alpine AS build

# Set the working directory to /app
WORKDIR /app

# Copy the package.json and package-lock.json into the container
COPY package*.json ./

# Install any needed dependencies including dev dependencies
RUN npm install

# Copy the current directory contents into the container at /app
COPY . .

# Build the TypeScript project
RUN npm run build

# Use a smaller Node.js runtime for the production environment
FROM node:18-alpine AS production

# Set the working directory to /app
WORKDIR /app

# Copy only the production dependencies from the build stage
COPY --from=build /app/node_modules ./node_modules

# Copy the built application from the build stage
COPY --from=build /app/dist ./dist

# Environment variables for Brevo MCP
ENV NODE_ENV=production

# Run the application
ENTRYPOINT ["node", "dist/index.js"]
